name: Deploy

on:
  workflow_dispatch:
  push:

jobs:
  run_python:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Python Script
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx_rtd_theme
          cd AsyncPywhatKit/docs
          sphinx-apidoc -o . ..
          make clean html
          make html
          git add .
          git commit -m "Generated documentation"
          git push gh-pages
